# Generated by Django 5.0.3 on 2025-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
